const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),crypto=require('crypto');
const cache=new Map(),properties=new Map([['SECRET_PEPPER','test-only']]);let stored;
const ctx={console,Date,CacheService:{getScriptCache:()=>({get:k=>cache.get(k),put:(k,v)=>cache.set(k,v),remove:k=>cache.delete(k)})},PropertiesService:{getScriptProperties:()=>({getProperty:k=>properties.get(k)})},Utilities:{getUuid:()=>crypto.randomUUID(),base64Encode:b=>Buffer.from(b).toString('base64'),computeHmacSha256Signature:(v,k)=>crypto.createHmac('sha256',k).update(v).digest()}};vm.createContext(ctx);for(const f of ['Core.gs','Code.gs','Pdf.gs'])vm.runInContext(fs.readFileSync(__dirname+'/../'+f,'utf8'),ctx);ctx.withLock_=f=>f();ctx.readState_=()=>structuredClone(stored);ctx.writeState_=s=>{stored=structuredClone(s);};
function fresh(){let s={version:1,seq:0,teacher:{salt:'t',hash:ctx.hash_('teacher-password','t'),version:1},students:['one','two','three'].map((id,i)=>({id,number:i+1,name:id,code:'CODE'+i,salt:id,hash:ctx.hash_('1234',id),authVersion:1,balance:1000,avatar:''})),auctions:[],bids:[],coupons:[],ledger:[],audit:[],requests:[]};return s;}
function auction(s,mode='public',id='a'){let a=ctx.newAuction_(s,{title:'쿠폰',mode,minimum:100,step:10,validDays:14,timing:'scheduled',start:1000,end:2000},0,id);a.paymentMode='internal';return a;}
let passed=0;function test(name,f){f();passed++;console.log('PASS '+name);}
test('공개 입찰 / 초과 금액 / 최고가 교체 시 묶임 해제',()=>{let s=fresh();auction(s);ctx.placeBid_(s,'one',{auction:'a',amount:300},1100);assert.equal(ctx.held_(s,'one'),300);assert.throws(()=>ctx.placeBid_(s,'two',{auction:'a',amount:300},1101));ctx.placeBid_(s,'two',{auction:'a',amount:310},1102);assert.equal(ctx.held_(s,'one'),0);assert.equal(ctx.held_(s,'two'),310);assert.throws(()=>ctx.placeBid_(s,'one',{auction:'a',amount:1100},1103));});
test('비공개 수정 / 철회 / 동점 선접수',()=>{let s=fresh(),a=auction(s,'sealed');ctx.placeBid_(s,'one',{auction:'a',amount:300},1100);ctx.placeBid_(s,'two',{auction:'a',amount:300},1100);assert.equal(ctx.ranked_(s,a)[0].student,'one');ctx.placeBid_(s,'one',{auction:'a',amount:200},1101);ctx.placeBid_(s,'one',{auction:'a',amount:300},1102);assert.equal(ctx.ranked_(s,a)[0].student,'two');ctx.placeBid_(s,'two',{auction:'a',amount:0},1103);assert.equal(ctx.held_(s,'two'),0);});
test('여러 경매의 중복 지출 방지',()=>{let s=fresh();auction(s,'sealed');auction(s,'sealed','b');ctx.placeBid_(s,'one',{auction:'a',amount:700},1100);assert.throws(()=>ctx.placeBid_(s,'one',{auction:'b',amount:400},1100));ctx.placeBid_(s,'one',{auction:'b',amount:300},1100);assert.equal(ctx.held_(s,'one'),1000);});
test('마감 경계 / 한 번만 정산 / 쿠폰 한 장',()=>{let s=fresh();auction(s);assert.throws(()=>ctx.placeBid_(s,'one',{auction:'a',amount:100},999));ctx.placeBid_(s,'one',{auction:'a',amount:400},1999);assert.throws(()=>ctx.placeBid_(s,'two',{auction:'a',amount:410},2000));assert.equal(ctx.settle_(s,2000),true);ctx.settle_(s,2100);assert.equal(s.students[0].balance,600);assert.equal(s.ledger.length,1);assert.equal(s.coupons.length,1);assert.equal(ctx.held_(s,'one'),0);});
test('취소 경매와 유찰은 차감 없음',()=>{let s=fresh();let a=auction(s);ctx.placeBid_(s,'one',{auction:'a',amount:300},1100);a.status='cancelled';ctx.settle_(s,2100);assert.equal(s.students[0].balance,1000);assert.equal(ctx.held_(s,'one'),0);let b=auction(s,'sealed','b');ctx.settle_(s,2200);assert.equal(b.winner,'');assert.equal(s.coupons.length,0);});
test('참여 학생 제한 / GOLD 차감 제한',()=>{let s=fresh(),a=auction(s);a.allowed=['one'];assert.throws(()=>ctx.placeBid_(s,'two',{auction:'a',amount:300},1100));ctx.placeBid_(s,'one',{auction:'a',amount:300},1100);assert.throws(()=>ctx.changeGold_(s,{rows:[{id:'one',amount:-800}],reason:'조정'},1100,'x'));ctx.changeGold_(s,{rows:[{id:'one',amount:-700}],reason:'조정'},1100,'x');assert.equal(s.students[0].balance,300);});
test('비공개 최고가와 다른 학생 입찰은 학생 응답에 없음',()=>{let s=fresh();auction(s,'sealed');ctx.placeBid_(s,'two',{auction:'a',amount:800},1100);let r=ctx.snapshot_(s,{role:'student',id:'one'});assert.equal(r.auctions[0].highest,0);assert.equal(r.auctions[0].leader,'');assert.equal(r.students.length,0);assert(!JSON.stringify(r).includes('1234'));assert(!JSON.stringify(r).includes('CODE1'));});
test('계정 중복 / PIN 선행 0 / 기존 아이디 충돌',()=>{let s=fresh();assert.throws(()=>ctx.validateImport_(s,[{number:1,code:'AAAA',pin:'1234'},{number:1,code:'BBBB',pin:'1234'}]));assert.throws(()=>ctx.validateImport_(s,[{number:1,code:'CODE1',pin:'1234'}]));assert.equal(ctx.validateImport_(s,[{number:1,code:'NEWW',pin:'0123'}])[0].pin,'0123');});
test('실제 API의 교사 권한 검사 / 학생은 GOLD 변경 금지',()=>{stored=fresh();let r=ctx.api('login','',{role:'student',code:'CODE0',password:'1234'});assert(r.ok);let no=ctx.api('gold',r.data.token,{requestId:crypto.randomUUID(),rows:[{id:'one',amount:999}],reason:'bad'});assert.equal(no.ok,false);assert.equal(stored.students[0].balance,1000);assert.equal(ctx.api('snapshot','forged',{}).ok,false);});
test('외부 정산 모드에서 GOLD 지급 API 차단',()=>{stored=fresh();let token=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token,p={requestId:crypto.randomUUID(),rows:[{id:'one',amount:100}],reason:'보상'};assert.equal(ctx.api('gold',token,p).ok,false);assert.equal(stored.students[0].balance,1000);assert.equal(stored.ledger.length,0);});
test('PDF 계정 변경 후 이전 세션 무효 / GOLD 유지',()=>{stored=fresh();let st=ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).data.token,t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;let r=ctx.api('accounts',t,{requestId:crypto.randomUUID(),rows:[{number:1,name:'새이름',code:'NEW1',pin:'0123'}]});assert(r.ok);assert.equal(stored.students[0].balance,1000);assert.equal(ctx.api('snapshot',st,{}).ok,false);assert(ctx.api('login','',{role:'student',code:'NEW1',password:'0123'}).ok);});
test('교사 비밀번호 변경 / 이전 세션 무효',()=>{stored=fresh();let t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;assert(ctx.api('password',t,{requestId:crypto.randomUUID(),current:'teacher-password',next:'new-teacher-password'}).ok);assert.equal(ctx.api('snapshot',t,{}).ok,false);assert(ctx.api('login','',{role:'teacher',password:'new-teacher-password'}).ok);});
test('로그인 5회 실패 후 잠금',()=>{stored=fresh();cache.clear();for(let i=0;i<5;i++)assert.equal(ctx.api('login','',{role:'student',code:'CODE0',password:'bad'}).ok,false);assert.equal(ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).ok,false);});
test('OCR 표준 텍스트 추출 / 번호 모호하면 빈 번호',()=>{const r=ctx.parseLoginText_('1번\n학생코드: ABCD12\n2차 PIN: 0123\n2번\n학생코드: DEFG34\n2차 PIN: 4567');assert.equal(r.length,2);assert.equal(r[0].number,1);assert.equal(r[1].number,2);assert.equal(r[0].pin,'0123');const amb=ctx.parseLoginText_('1번\n2번\n학생코드: ABCD12\n2차 PIN: 0123');assert.equal(amb[0].number,'');});
test('쿠폰 요청·승인 후 재승인 금지',()=>{stored=fresh();stored.coupons=[{id:'coupon:test',student:'one',title:'간식',expiry:Date.now()+60000,status:'unused'}];cache.clear();let st=ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).data.token,t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;assert(ctx.api('requestCoupon',st,{id:'coupon:test',requestId:crypto.randomUUID()}).ok);assert(ctx.api('coupon',t,{id:'coupon:test',approve:true,requestId:crypto.randomUUID()}).ok);assert.equal(ctx.api('coupon',t,{id:'coupon:test',approve:true,requestId:crypto.randomUUID()}).ok,false);assert.equal(stored.coupons[0].status,'used');});
test('저장 실패 시 메모리 변경이 실제 데이터에 반영되지 않음',()=>{stored=fresh();cache.clear();let t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token,save=ctx.writeState_;ctx.writeState_=()=>{throw Error('storage unavailable');};let r=ctx.api('gold',t,{requestId:crypto.randomUUID(),rows:[{id:'one',amount:100}],reason:'보상'});assert.equal(r.ok,false);assert.equal(stored.students[0].balance,1000);ctx.writeState_=save;});
test('학생 계정 수동 수정 / PIN 공란은 유지 / 학생 번호 불변',()=>{stored=fresh();cache.clear();let t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token,hash=stored.students[0].hash;let r=ctx.api('updateStudent',t,{requestId:crypto.randomUUID(),id:'one',number:9,name:'별명',code:'NEWCODE',pin:''});assert(r.ok);assert.equal(stored.students[0].number,1);assert.equal(stored.students[0].balance,1000);assert.equal(stored.students[0].hash,hash);assert(ctx.api('login','',{role:'student',code:'NEWCODE',password:'1234'}).ok);});
test('수동 PIN 변경 / 옛 PIN 거절 / 교사 전용',()=>{stored=fresh();cache.clear();let st=ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).data.token,t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;const p={requestId:crypto.randomUUID(),id:'one',name:'one',code:'CODE0',pin:'0012'};assert.equal(ctx.api('updateStudent',st,p).ok,false);assert(ctx.api('updateStudent',t,p).ok);assert.equal(ctx.api('snapshot',st,{}).ok,false);assert.equal(ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).ok,false);assert(ctx.api('login','',{role:'student',code:'CODE0',password:'0012'}).ok);});
test('수동 아이디 중복은 거절하고 원래 계정 유지',()=>{stored=fresh();cache.clear();let t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;assert.equal(ctx.api('updateStudent',t,{requestId:crypto.randomUUID(),id:'one',code:'CODE1',name:'one',pin:''}).ok,false);assert.equal(stored.students[0].code,'CODE0');});
test('OCR 대체 라벨 / 누락 PIN / 반복 번호 처리',()=>{let r=ctx.parseLoginText_('8번\n8번\n학생 아이디: abcd12\n비밀번호: 0012');assert.equal(r[0].number,8);assert.equal(r[0].code,'ABCD12');assert.equal(r[0].pin,'0012');r=ctx.parseLoginText_('4번\n학생코드: AAAA11');assert.equal(r.length,1);assert.equal(r[0].pin,'');});
test('외부 방식: 잔액 0이어도 입찰 / 여러 경매 / 차감 없음',()=>{let s=fresh();s.students[0].balance=0;let a=auction(s,'sealed'),b=auction(s,'public','b');ctx.enableExternalPayment_(s,1001);ctx.placeBid_(s,'one',{auction:'a',amount:5000},1100);ctx.placeBid_(s,'one',{auction:'b',amount:9000},1101);assert.equal(ctx.held_(s,'one'),0);ctx.settle_(s,2000);assert.equal(s.students[0].balance,0);assert.equal(s.ledger.length,0);assert.equal(s.coupons.length,2);assert.equal(s.coupons[0].status,'paymentPending');assert.equal(a.paymentStatus,'pending');});
test('전환 시 진행 경매만 변경 / 종료 기록 유지 / 한 번만 전환',()=>{let s=fresh(),a=auction(s),b=auction(s,'public','b');a.status='closed';a.price=200;const before=s.students[0].balance;assert(ctx.enableExternalPayment_(s,1000));assert.equal(a.paymentMode,'internal');assert.equal(b.paymentMode,'external');assert.equal(s.students[0].balance,before);assert.equal(ctx.enableExternalPayment_(s,1100),false);});
test('외부 처리 확인은 교사만 가능 / 재전송 중복 방지 / 쿠폰 활성화',()=>{stored=fresh();cache.clear();let a=auction(stored);a.paymentMode='external';ctx.placeBid_(stored,'one',{auction:'a',amount:5000},1100);ctx.settle_(stored,2000);let st=ctx.api('login','',{role:'student',code:'CODE0',password:'1234'}).data.token,t=ctx.api('login','',{role:'teacher',password:'teacher-password'}).data.token;const p={id:'a',note:'학급 홈페이지에서 차감 완료',requestId:crypto.randomUUID()};assert.equal(ctx.api('payment',st,p).ok,false);assert.equal(ctx.api('requestCoupon',st,{id:'coupon:a',requestId:crypto.randomUUID()}).ok,false);assert(ctx.api('payment',t,p).ok);assert(ctx.api('payment',t,p).ok);assert.equal(stored.auctions[0].paymentStatus,'paid');assert.equal(stored.coupons[0].status,'unused');assert.equal(stored.students[0].balance,1000);assert.equal(stored.ledger.length,0);assert.equal(stored.audit.filter(x=>x.action==='payment').length,1);assert(ctx.api('requestCoupon',st,{id:'coupon:a',requestId:crypto.randomUUID()}).ok);});
console.log(passed+' tests passed');
