const {JSDOM,VirtualConsole}=require('jsdom'),fs=require('fs'),assert=require('assert/strict');
const html=fs.readFileSync(__dirname+'/../Index.html','utf8');let calls=[],errors=[];
const fixture={role:'teacher',serverNow:Date.now(),me:null,students:[{id:'u1',number:1,name:'학생1',code:'DEMO1',balance:500,held:0,avatar:''}],auctions:[],coupons:[],ledger:[],audit:[]};
const vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));
const dom=new JSDOM(html,{url:'https://example.test',runScripts:'dangerously',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){w.HTMLElement.prototype.scrollIntoView=function(){};w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'));};const runner={withSuccessHandler(fn){const r=Object.create(this);r.success=fn;return r;},withFailureHandler(fn){this.failure=fn;return this;},api(action,token,p){calls.push({action,token,p});let result=action==='login'?{token:'test-token',role:p.role}:action==='pdf'?{text:'demo',rows:[{number:1,name:'학생1',code:'NEW01',pin:'0012'}],warning:'원본 대조 필요'}:fixture;Promise.resolve().then(()=>this.success({ok:true,data:result}));}};w.google={script:{run:runner}};}});
const w=dom.window,$=s=>w.document.querySelector(s),turn=()=>new Promise(r=>setTimeout(r,30));function input(el,value){el.value=value;el.dispatchEvent(new w.Event('input',{bubbles:true}));}function submit(el){el.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
(async()=>{
assert(w.document.body.classList.contains('auth-page'));assert($('#login-submit').disabled);input($('#auth-input'),'demo1');assert(!$('#login-submit').disabled);submit($('#login-form'));assert.equal($('.auth-wrap h1').textContent,'2차 PIN 인증');assert.equal(calls.length,0);assert.equal($('#auth-input').type,'password');input($('#auth-input'),'0012');assert(!$('#login-submit').disabled);$('#auth-back').click();assert.equal($('#auth-input').value,'DEMO1');$('#auth-back').click();assert.equal($('.auth-wrap h1').textContent,'교사 로그인');input($('#auth-input'),'teacher-password');submit($('#login-form'));await turn();assert(!w.document.body.classList.contains('auth-page'));assert.equal(calls[0].p.role,'teacher');console.log('PASS two-step login, back navigation and teacher authentication flow');
$('[data-nav=accounts]').click();assert($('[data-edit-student="u1"]'));$('[data-edit-student="u1"]').click();assert.equal($('#student-editor [name=code]').value,'DEMO1');assert.equal($('#edit-pin').value,'');input($('#student-editor [name=name]'),'별명');submit($('#student-editor'));$('#confirm-yes').click();await turn();assert.equal(calls.at(-1).action,'updateStudent');assert.equal(calls.at(-1).p.pin,'');assert.equal(calls.at(-1).p.name,'별명');console.log('PASS manual edit submits blank PIN without changing student identity');
$('#manual-account').click();assert($('#import-body tr'));const first=$('#import-body tr');input(first.querySelector('[data-field=number]'),'2');input(first.querySelector('[data-field=name]'),'학생2');input(first.querySelector('[data-field=code]'),'DEMO2');input(first.querySelector('[data-field=pin]'),'0012');assert.equal(first.dataset.valid,'true');$('#select-import').checked=true;$('#select-import').dispatchEvent(new w.Event('change'));assert(first.querySelector('[data-field=checked]').checked);$('#toggle-pins').click();assert.equal(first.querySelector('[data-field=pin]').type,'text');$('#apply-accounts').click();$('#confirm-yes').click();await turn();assert.equal(calls.at(-1).action,'accounts');assert.equal(calls.at(-1).p.rows[0].pin,'0012');console.log('PASS manual registration, selection and PIN visibility');
$('#manual-account').click();const tr=$('#import-body tr');input(tr.querySelector('[data-field=number]'),'3');input(tr.querySelector('[data-field=code]'),'DEMO3');input(tr.querySelector('[data-field=pin]'),'12');$('#select-import').checked=true;$('#select-import').dispatchEvent(new w.Event('change'));assert.equal(tr.querySelector('[data-field=checked]').checked,false);assert.equal(tr.dataset.valid,'false');console.log('PASS invalid account rows are excluded from select-all');
assert.equal($('[data-nav=gold]'),null);fixture.auctions=[{id:'pay1',title:'간식',status:'closed',winner:'학생1',winnerNumber:1,price:5000,paymentMode:'external',paymentStatus:'pending'}];$('[data-nav=manage]').click();$('[data-nav=payments]').click();assert($('#main').textContent.includes('5,000 GOLD'));w.prompt=()=> '학급 홈페이지 처리 완료';$('[data-payment=pay1]').click();$('#confirm-yes').click();await turn();assert.equal(calls.at(-1).action,'payment');assert.equal(calls.at(-1).p.id,'pay1');console.log('PASS external payment display and teacher confirmation');
fixture.role='student';fixture.me={id:'u1',name:'학생1',number:1,balance:0,held:0,avatar:''};w.eval("data=JSON.parse('"+JSON.stringify(fixture)+"');view='market';render();");assert.equal($('[data-nav=wallet]'),null);assert(!$('#main').textContent.includes('사용 가능한 GOLD'));assert($('#main').textContent.includes('잔액 확인이나 GOLD 차감을 하지 않아요'));console.log('PASS student bidding-only screen has no wallet or balance requirement');
assert.deepEqual(errors,[]);dom.window.close();console.log('6 UI flow tests passed');
})().catch(e=>{console.error(e);dom.window.close();process.exitCode=1;});
